#!/usr/bin/env bash

if [ ! -z "$WWWGROUP" ]; then
    usermod -u $WWWGROUP nocker
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER nocker
fi

if [ ! -d /.npm ]; then
    mkdir /.npm
fi

chmod -R ugo+rw /.npm
